### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by AObuchow**
@ingomohr can this be safely deleted from the repo now? (I don't think it's being used)

### CODE REVIEW

**Comment by ingomohr** [comment]
> @ingomohr can this be safely deleted from the repo now? (I don't think it's being used)

@AObuchow Yes, I think so. With the workflow, we now have our own CI integration, and we don‘t need two of them. However, Travis tests every branch and PR. Our workflow (atm) runs only when master changes - but we could change that.
I could create a PR for you tonight which deletes Travis and updates the workflow to test PRs and branches, too.
What do you think?

**Comment by AObuchow** [comment]
> > @ingomohr can this be safely deleted from the repo now? (I don't think it's being used)
> 
> @AObuchow Yes, I think so. With the workflow, we now have our own CI integration, and we don‘t need two of them. However, Travis tests every branch and PR. Our workflow (atm) runs only when master changes - but we could change that.
> I could create a PR for you tonight which deletes Travis and updates the workflow to test PRs and branches, too.
> What do you think?

Sure sounds good :) feel free to message me more details about the updated workflow so I have a good idea of what it will change (maybe on a github issue? Or twitter DM, whatever works for you)

**Comment by ingomohr** [comment]
> > > @ingomohr can this be safely deleted from the repo now? (I don't think it's being used)
> > 
> > @AObuchow Yes, I think so. With the workflow, we now have our own CI integration, and we don‘t need two of them. However, Travis tests every branch and PR. Our workflow (atm) runs only when master changes - but we could change that.
> > I could create a PR for you tonight which deletes Travis and updates the workflow to test PRs and branches, too.
> > What do you think?
> 
> Sure sounds good :) feel free to message me more details about the updated workflow so I have a good idea of what it will change (maybe on a github issue? Or twitter DM, whatever works for you)

From my perspective, we have 2 options:
1: We test each branch and PR, but only deploy an updatesite when master changes (easy way)
2: We test each branch and PR and deploy updatesites also for each branch and PR. We would have to cleanup the branch/PR updates - for which we need some nice solution to come up with. 😉 (but this is the better goal, I think)

**Comment by ingomohr** [comment]
If the permission settings allow this, you could assign the issue to me so I can find it faster to add comments. (but no deal breaker 😉)

**Comment by AObuchow** [comment]
@ingomohr sounds good - I’ll make an issue about adding a github action for PR’s and reference our discussion here :)

**Pull request closed without merging**
